---
- name: Run mario
  gather_facts: true
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tags:
  - mario

  tasks:
    - name: Start mario
      community.docker.docker_container:
        name: mario
        image: pengbai/docker-supermario
        exposed_ports:
          - 8080 
        publish_all_ports : true