---
- name: Run mario
  gather_facts: true
  hosts: prod

  tasks:
    - name: Start mario
      community.docker.docker_container:
        name: mario
        image: pengbai/docker-supermario
        exposed_ports:
          - 8080 