---
- name: install website
  hosts: prod
  become: true
  become_user: root

  tasks:

  - name: "Clean Folder"
    file:
      path: /home/vagrant/webapp/
      state: absent

  - name: recreate directory 
    file:
      state: directory
      path: /home/vagrant/webapp/

  - name: Example clone of a single branch
    ansible.builtin.git:
      repo: https://github.com/diranetafen/static-website-example.git
      dest: /home/vagrant/webapp/

  - name: Use template for index.html
    template:
      src: "index.html"
      dest: "/home/vagrant/webapp/index.html"
      mode: 0644