all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: vagrant
  children:
    prod:
      vars:
        env: prod
        ansible_password: vagrant
      hosts:
        client2:
          ansible_host: 192.168.99.12
          ansible_port: 22
    server:
      vars:
        ansible_connection: local
      hosts:
        ansible:
          ansible_host: 192.168.99.10
        