all:
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_user: vagrant
  children:
    prod:
      vars:
        env: prod
        ansible_password: vagrant
      hosts:
        client1:
          ansible_host: 192.168.99.11
        client2:
          ansible_host: 192.168.99.12
  hosts:
    hosts:
      ansible:
        ansible_host: 192.168.99.11