- gather_facts: yes
  hosts: prod
  vars_files:
    - /vars/external_vars.yml

- import_playbook: nginx.yml

- import_playbook: webapp.yml
  when: ansible_distribution == "CentOS"

#- import_playbook: webapp_debian.yml
#  when: ansible_distribution == "debian"
