---
- name: install_dependencies
  hosts: prod
  become: true
  become_user: root
  vars_files:
    - files/secrets/credentials.yml

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present

  - name: Install git
    ansible.builtin.package:
      name: git
      state: present

  - name: run service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes