---
- name: install website
  hosts: prod
  become: true
  become_user: root
  vars_files:
    - files/secrets/credentials.yml

  tasks:
  - name: Use template for index.html
    template:
      src: "index.html"
      dest: "/usr/share/nginx/html/"
      mode: 0644
    notify:
    - Restart nginx

  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted