all:
  children:
    client:
      hosts:
        client1:
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_host: 192.168.99.11
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
        client2:
          ansible_user: vagrant
          ansible_password: vagrant
          ansible_host: 192.168.99.12
          ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    prod:
      children:
        client: