- gather_facts: yes
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3

- import_playbook: nginx.yml

- import_playbook: webapp.yml
  when: ansible_distribution == "CentOS"

#- import_playbook: webapp_debian.yml
#  when: ansible_distribution == "debian"
