---
- name: install
  hosts: prod
  become: true
  become_user: root

  tasks:
  - name: Install nginx
    ansible.builtin.package:
      name: nginx
      state: present
    notify:
      - install nginx

  handlers:
    - name: install nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes